accounts/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accounts.views import RegisterView, ProfileView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import CreateTopic, TopicsList, TopicDetail, AnswerAdd, AnswerUpdate, AnswerDelete, TopicUpdate, TopicDelete

app_name = "webapp"

urlpatterns = [
    path('', TopicsList.as_view(), name="topics_list"),
    path('topic/add/', CreateTopic.as_view(), name="topic_add"),
    path('topic/<int:pk>/', TopicDetail.as_view(), name="topic_view"),
    path('topic/<int:pk>/update/', TopicUpdate.as_view(), name="topic_update"),
    path('topic/<int:pk>/delete/', TopicDelete.as_view(), name="topic_delete"),
    path('topic/<int:pk>/add-answer/', AnswerAdd.as_view(), name="add_answer"),
    path('answer/<int:pk>/delete/', AnswerDelete.as_view(), name="delete_answer"),
    path('answer/<int:pk>/update/', AnswerUpdate.as_view(), name="update_answer"),
]

webapp/models/answers.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from webapp.models import BaseCreateUpdateModel


class Answer(BaseCreateUpdateModel):
    answer = models.TextField(verbose_name='Ответ')
    topic = models.ForeignKey('webapp.Topic', on_delete=models.CASCADE, related_name='answers',verbose_name='Тема')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='answers',verbose_name='Автор')

    class Meta:
        db_table = 'answers'
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"


    def __str__(self):
        return self.answer

    def get_absolute_url(self):
        return reverse('webapp:topic_view', kwargs={'pk': self.topic_id})

webapp/models/topics.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from webapp.models import BaseCreateUpdateModel


class Topic(BaseCreateUpdateModel):
    topic = models.CharField(verbose_name='Название', max_length=100)
    content = models.TextField(verbose_name='Содержимое')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='topics',verbose_name='Автор')

    class Meta:
        db_table = 'topics'
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'

    def __str__(self):
        return self.topic

    def get_absolute_url(self):
        return reverse('webapp:topic_view', kwargs={'pk': self.pk})

webapp/forms/topics.py
from webapp.forms import BaseForm
from webapp.models import Topic


class TopicForm(BaseForm):
    class Meta:
        model = Topic
        fields = ['topic', 'content',]

webapp/views/topics.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from webapp.forms import TopicForm, AnswerForm
from webapp.models import Topic


class CreateTopic(LoginRequiredMixin, CreateView):
    form_class = TopicForm
    template_name = 'topics/create_topic.html'
    success_url = reverse_lazy('webapp:topics_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TopicsList(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'topics/topics_list.html'
    ordering = '-created_at'
    paginate_by = 2


class TopicDetail(DetailView, MultipleObjectMixin):
    model = Topic
    template_name = 'topics/topic_detail.html'
    paginate_by = 2


    def get_context_data(self, **kwargs):
        topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        object_list = topic.answers.all()
        answer_form = self.get_answer_form(self.request)
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['answer_form'] = answer_form['answer_form']
        return context

    def get_answer_form(self, request):
        return {'answer_form': AnswerForm(request.GET)}



class TopicUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'topics/topic_update.html'
    model = Topic
    form_class = TopicForm
    permission_required = 'webapp.change_topic'

    def has_permission(self):
        topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return super().has_permission() or topic.author == self.request.user



class TopicDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'topics/topic_delete.html'
    model = Topic
    permission_required = 'webapp.delete_topic'
    success_url = reverse_lazy('webapp:topics_list')

    def has_permission(self):
        topic = get_object_or_404(Topic, pk=self.kwargs['pk'])
        return super().has_permission() or topic.author == self.request.user

templates/topics/create_topic.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавить тему</title>
{% endblock %}

{% block content %}
    {% include 'partial/form.html' with btn_text='Добавить'%}
{% endblock %}

templates/topics/topic_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Удалить тему</title>
{% endblock %}

{% block content%}
    <form action="" method="post">
{% csrf_token %}
    <p>Вы хотите удалить тему?</p>
        <a class="btn" href="{% url 'webapp:topic_view' topic.pk %}">Отмена</a>
    <button class="btn btn-outline-danger" type="submit">Да</button>
    </form>
{% endblock %}

templates/topics/topic_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">{{ topic.topic }}</h5>
            <p class="card-text">{{ topic.content}}</p>
            <p class="text-body-secondary">{{ topic.created_at }}</p>
            <a href="{% url 'accounts:profile' topic.author.pk %}"><p class="text-body-secondary">{{ topic.author }}</p></a>
            {% if perms.webapp.change_topic or request.user == topic.author %}
                <a href="{% url 'webapp:topic_delete' topic.pk %}" title="Удалить тему" ><i class="bi bi-trash3"></i></a>
            {% endif %}
            {% if perms.webapp.delete_topic or request.user == topic.author %}
                <a href="{% url 'webapp:topic_update' topic.pk %}" title="Редактировать тему"><i class="bi bi-pencil"></i></a>
            {% endif %}
        </div>
    </div>

{#    <form action="">#}
{#        {% include 'partial/form.html' with btn_text='Добавить'%}#}
{#    </form>#}


    <div class="container mt-3">
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'webapp:add_answer' topic.pk %}">
                {% csrf_token %}
                {{ answer_form.as_p }}
                <button type="submit" class="btn btn-primary">Ответить</button>
            </form>
        {% endif %}
        <div class="list-group mt-3">
            {% for answer in object_list %}
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ answer.author.avatar.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <a href="{% url 'accounts:profile' answer.author.pk %}"><h5 class="card-title">{{ answer.author }}</h5></a>
                                <p class="card-text">{{ answer.answer }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{ answer.created_at }}</small></p>
                                {% if perms.webapp.change_answer or request.user == answer.author %}
                                    <a href="{% url 'webapp:update_answer' answer.pk %}" title="Редактировать"><i class="bi bi-pencil"></i></a>
                                {% endif %}
                                {% if perms.webapp.delete_answer or request.user == answer.author %}
                                    <a href="{% url 'webapp:delete_answer' answer.pk %}" title="Удалить"><i class="bi bi-trash3"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

            {% empty %}
                Ответов пока нет
            {% endfor %}
        {%  if is_paginated %}
                {% include 'partial/pagination.html' %}
        {% endif %}
        </div>
    </div>

{% endblock %}

templates/topics/topic_update.html
{% extends 'base.html' %}

{% block title %}
    <title>Редактировать тему</title>
{% endblock %}

{% block content %}
    {% include 'partial/form.html' with btn_text='Редактировать'%}
{% endblock %}

templates/topics/topics_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content %}
    <h5 style="text-align: center">Темы</h5>
    {% for topic in topics %}
       <a style="text-decoration: none" href="{% url 'webapp:topic_view' topic.pk %}">
            <table class="table" >
                    <tbody>
                        <tr>
                            <th>{{ topic.topic }}</th>
                            <td>{{ topic.created_at }}</td>
                            <td>{{ topic.author }}</td>
                            <td>Ответов {{ topic.answers.count }}</td>
                        </tr>
                  </tbody>
            </table>
       </a>
    {% empty %}
        Темы еще не добавлены
    {% endfor %}

    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}