accounts/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accounts.views import RegisterView, ProfileView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import CreateTopic, TopicsList, TopicDetail, AnswerAdd, AnswerUpdate, AnswerDelete, TopicUpdate, TopicDelete

app_name = "webapp"

urlpatterns = [
    path('', TopicsList.as_view(), name="topics_list"),
    path('topic/add/', CreateTopic.as_view(), name="topic_add"),
    path('topic/<int:pk>/', TopicDetail.as_view(), name="topic_view"),
    path('topic/<int:pk>/update/', TopicUpdate.as_view(), name="topic_update"),
    path('topic/<int:pk>/delete/', TopicDelete.as_view(), name="topic_delete"),
    path('topic/<int:pk>/add-answer/', AnswerAdd.as_view(), name="add_answer"),
    path('answer/<int:pk>/delete/', AnswerDelete.as_view(), name="delete_answer"),
    path('answer/<int:pk>/update/', AnswerUpdate.as_view(), name="update_answer"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class MyUser(AbstractUser):
    REQUIRED_FIELDS = [ 'password', 'avatar']
    avatar = models.ImageField(upload_to="avatars", verbose_name='Аватар')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'users'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class MyUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username', 'avatar', 'password1', 'password2',]

accounts/views.py
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView

from accounts.forms import MyUserCreationForm


class RegisterView(CreateView):
    template_name = "accounts/user_create.html"
    model = get_user_model()
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse('webapp:topics_list'))

class ProfileView(DetailView):
    template_name = 'accounts/profile_view.html'
    model = get_user_model()
    context_object_name = 'user_obj'

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h5>Вход</h5>
    {% include 'partial/form.html' with btn_text='Войти'%}
{% endblock %}

templates/accounts/profile_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4 align-middle d-flex w-50  justify-content-between" style="">
                <img src="{{ user_obj.avatar.url }}" class="img-fluid" style="max-width: 200px;" alt="...">
                <h6 class="card-title">{{ user_obj.username}}</h6>

            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p>Комментариев {{ user_obj.answers.count }}</p>
                </div>
            </div>
        </div>
    </div>

{% for topic in user_obj.topics.all %}
    <div class="list-group">
        <a href="{% url 'webapp:topic_view' topic.pk %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-70 justify-content-between">
                <h5 class="mb-1">{{ topic.topic }}</h5>
                <small class="text-body-secondary">{{ topic.created_at }}</small>
            </div>
            <small class="text-body-secondary">Ответов - {{ topic.answers.count }}</small>
        </a>
    </div>
{% empty %}
    Темы еще не добавлены
{% endfor %}








{#    <div class="card-group d-flex flex-column" style="width: auto" >#}
{##}
{#            <div class="card" style="max-width: 18rem;">#}
{#                <a href="{% url 'webapp:topic_view'  topic.pk %}">{{ topic.topic }}</a>#}
{#            </div>#}
{##}
{#    </div>#}
{% endblock %}

templates/accounts/user_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Регистрация</title>
{% endblock %}

{% block content %}
    <h5>Регистрация</h5>
    <div class="container" style="text-align: center">
        {% include 'partial/form.html' with btn_text='Зарегистрироваться'%}
    </div>

{% endblock %}