accounts/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from accounts.views import RegisterView, ProfileView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
]

forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import CreateTopic, TopicsList, TopicDetail, AnswerAdd, AnswerUpdate, AnswerDelete, TopicUpdate, TopicDelete

app_name = "webapp"

urlpatterns = [
    path('', TopicsList.as_view(), name="topics_list"),
    path('topic/add/', CreateTopic.as_view(), name="topic_add"),
    path('topic/<int:pk>/', TopicDetail.as_view(), name="topic_view"),
    path('topic/<int:pk>/update/', TopicUpdate.as_view(), name="topic_update"),
    path('topic/<int:pk>/delete/', TopicDelete.as_view(), name="topic_delete"),
    path('topic/<int:pk>/add-answer/', AnswerAdd.as_view(), name="add_answer"),
    path('answer/<int:pk>/delete/', AnswerDelete.as_view(), name="delete_answer"),
    path('answer/<int:pk>/update/', AnswerUpdate.as_view(), name="update_answer"),
]

webapp/forms/base_form.py
from django import forms
from django.forms import widgets


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for v in self.visible_fields():
            if not isinstance(v.field.widget, widgets.CheckboxSelectMultiple):
                v.field.widget.attrs['class'] = 'form-control'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Base</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'webapp:topics_list' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'webapp:topic_add' %}">Добавить тему</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn nav-link active">Выйти</button>
                    </form>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' request.user.pk %}">Личный кабинет</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:registration' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block nav %}
{% endblock %}
<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>